models/contact.py
from utils.db import db


class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(100))
    email = db.Column(db.String(100))
    phone = db.Column(db.String(100))

    def __init__(self,fullname, email,phone):
        self.fullname = fullname
        self.email = email
        self.phone = phone

app.py
from flask import Flask
from routes.contacts import contacts
from utils.db import db
from config import user, password, host, database

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = f'mysql://{user}:{password}@{host}/{database}'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.secret_key = 'secret key'
db.init_app(app)
app.register_blueprint(contacts)

with app.app_context():
    try:
        db.create_all()
    except Exception as e:
        print(e)
if __name__ == "__main__":
    app.run(debug=True)

routes/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.contact import Contact
from utils.db import db

contacts = Blueprint('contacts', __name__)


@contacts.route('/')
def home():
    contacts = Contact.query.all()
    return render_template('index.html', contacts=contacts)


@contacts.route('/new', methods=['POST'])
def new():
    fullname = request.form['fullname']
    email = request.form['email']
    phone = request.form['phone']
    new_contact = Contact(fullname, email, phone)
    db.session.add(new_contact)
    db.session.commit()
    flash('contacto agregado')
    return redirect('/')


@contacts.route('/update/<id>', methods=['POST', 'GET'])
def update(id):
    contact = Contact.query.get(id)
    if request.method == 'POST':
        contact.fullname = request.form['fullname']
        contact.email = request.form['email']
        contact.phone = request.form['phone']
        db.session.commit()
        flash('contacto actualizado')
        return redirect(url_for('contacts.home'))

    return render_template('update.html', contact=contact)


@contacts.route('/delete/<id>')
def delete(id):
    contact = Contact.query.get(id)
    db.session.delete(contact)
    db.session.commit()
    flash('contacto eliminado')
    return redirect(url_for('contacts.home'))


@contacts.route('/about')
def about():
    return "hello about"

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SQL ALCHEMY CRUD</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/main.css')}}"
    />
</head>
<body>
    {% include('partials/navbar.html') %}
    <div class="container p-2">
      {% block content %}
      {% endblock %}
    </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
    <div class="col-md-5">
        {% include 'partials/message.html '  %}
        {% include 'partials/contenform.html '%}
    </div>
    <div class="col-md-7">

            {% for contact in contacts %}
                <div class="card mb-1 bg-black text-white">
                    <div class="card-body py-2 px-3">
                        <div class="d-flex justify-content-between">
                        <h6>{{ contact.fullname }}</h6>
                                <div>
                            <a href="{{ url_for('contacts.update', id=contact.id)}}" class="btn btn-primary btn-sm rounded-0">Update</a>
                            <a href="{{ url_for('contacts.delete', id=contact.id)}}" class="btn btn-danger btn-sm rounded-0">Delete</a>
                            </div>
                        </div>
                        <p>{{ contact.email }}</p>
                        <p>{{ contact.phone }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
</div>


{% endblock %}

templates/partials/contenform.html
<form action="/new" method="POST" class="card bg-black text-light">
    <div class="card-body p-4">
        <div class="mb-3">
        <label for="fullname">Write your full name</label>
        <input type="text" name="fullname" placeholder="Write your fullname" class="form-control rounded-0
         bg-dark border-0 text-white   ">
        </div>
        <div class="mb-3">
            <label for="email">Write your email</label>
            <input type="text" name="email" placeholder="Write your email" class="form-control rounded-0
         bg-dark border-0 text-white">
        </div>
        <div class="mb-3">
            <label for="phone">Write your phone</label>
            <input type="text" name="phone" placeholder="Write your phone" class="form-control rounded-0
         bg-dark border-0 text-white">
        </div>
    <button>Save</button>

    </div>
</form>

templates/partials/message.html
{% with messages = get_flashed_messages() %}

    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Ready!</strong> {{message}}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    {% endif %}

{% endwith %}

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">Flask alchemy CRUD</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto" >
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/about">About</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/update.html
{% extends "base.html" %} {% block content %}

<div class="col-md-4 offset-md-4">
  <div class="card card-body bg-dark text-white">
    <h1>Edit Task</h1>

    <form action="{{url_for('contacts.update', id=contact.id)}}" method="POST">
      <div class="mb-3">
        <label for="fullname">Write your fullname:</label>
        <input
          type="text"
          name="fullname"
          value="{{contact.fullname}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>
      <div class="mb-3">
        <label for="email">Write your email:</label>
        <input
          type="email"
          name="email"
          value="{{contact.email}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>
      <div class="mb-3">
        <label for="phone">Write your phone:</label>
        <input
          type="tel"
          name="phone"
          value="{{contact.phone}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>

      <button class="btn btn-primary">Update</button>
    </form>
  </div>
</div>

{% endblock %}